# Predit Gold Price

In [ ]:
import yfinance as yf 
import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.tsa.stattools import adfuller, acf, pacf
import seaborn as sns

In [7]:

end_date = '2025-08-25'
start_date = pd.to_datetime(end_date)-pd.DateOffset(365*8) # How about if i get more than 8 years of data?

df = yf.download(tickers='XAU',
                 start=start_date,
                 end=end_date,auto_adjust=False).stack()
df.index.names = ['date', 'ticker']

df.columns = df.columns.str.lower()

df

[*********************100%***********************]  1 of 1 completed
C:\Users\VAQ\AppData\Local\Temp\ipykernel_14796\800480183.py:6: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  end=end_date,auto_adjust=False).stack()

Price              adj close  close  high   low  open  volume
date       ticker
2017-08-28 XAU          3.76   3.76  4.00  3.48  3.49  377584
2017-08-29 XAU          3.87   3.87  3.91  3.64  3.86  182071
2017-08-30 XAU          4.21   4.21  4.40  3.79  3.92  209762
2017-08-31 XAU          3.79   3.79  4.30  3.70  4.29  181769
2017-09-01 XAU          3.68   3.68  3.98  3.42  3.90  195031
...                      ...    ...   ...   ...   ...     ...
2018-01-24 XAU          4.64   4.64  4.88  4.50  4.55  324635
2018-01-25 XAU          4.43   4.43  4.75  4.40  4.75  235351
2018-01-26 XAU          4.25   4.25  4.59  4.14  4.44  225552
2018-01-29 XAU          4.08   4.08  4.22  4.00  4.20  240501
2018-01-30 XAU          4.33   4.33  4.35  3.96  4.05  247606

[107 rows x 6 columns]

In [8]:
df.shape

(107, 6)

In [12]:
# df['date'] = pd.to_datetime(df['date'])
# df = df.sort_values('date').reset_index(drop=True)

# # Set index for time series
# df.set_index('date', inplace=True)

# We'll focus on 'Close' for the analysis
ts = df['close']